### ISSUE TITLE
implement SPI protocol in ARM firmware

### ISSUE THREAD

**Issue by mgeforce** [janhieber/WaterCtrl#10] opened 2016-05-06 07:48 UTC
Implement the SPI protocol (described in https://github.com/janhieber/WaterCtrl/blob/master/firmware/SPECS.md) in the ARM firmware.

**Comment by janhieber** [comment] 2016-05-09 08:50
This is a duplicate of #7 

I hope I find some time to do this, or maybe @dropedout can have a look at it.
Receiving the message over SPI works, so its basically a switch/case on the first message byte.
According to the SPECS, an action can be scheduled then. For example the measurement of a sensor, which reports the measured values back over SPI.

**Closed as completed by janhieber** 2016-05-09 08:50 UTC
